config/routes.rb
Babynotes::Application.routes.draw do
  
  devise_for :users

  root to: "pages#index"
  match '/faq', to: "pages#faq"
  match '/team', to: "pages#team"
  match '/privacy_policy', to: "pages#privacy_policy"

  resources :users, only: [:show]

  resources :babies do
    resources :measurements
    resources :events
  end

  resources :timeline, only: [:index]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-error">
      <strong>The form contains <%= pluralize(object.errors.full_unique_messages.count, "error") %>.</strong>
      <ul>
      <% object.errors.full_unique_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    <ul class="inline unstyled">
      <p>
        &copy; <%= link_to "BabyNotes", root_path, class: "footer-link" %> 2012 | 
        <%= link_to "Our Team", team_path, class: "footer-link" %> | 
        <%= link_to "FAQ", faq_path, class: "footer-link" %> | 
        <%= link_to "Privacy Policy", privacy_policy_path, class: "footer-link" %>
      </p>
    </ul>
  </small>
</footer>

app/views/shared/_nav_bar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BabyNotes", root_path, class: "brand" %>
      <ul class="nav pull-right">
        <% if current_user %>
          <%= render 'shared/nav_user' %>
        <% else %>
          <%= render 'shared/nav_login' %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_nav_login.html.erb
<li><%= link_to "Register", new_user_registration_path %></li>
<li><%= link_to "Sign in", new_user_session_path %></li>

app/views/shared/_nav_user.html.erb
<li><%= link_to "View Babies", babies_path %></li>
<li><%= link_to "View Profile", user_path(current_user) %></li>
<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>

app/views/shared/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

app/views/shared/_timelineHeader.html.erb
<header class="row fullwidth">
	<div class="col_3 logo">
		<%= image_tag "logo.png" %>
	</div>
	<nav class="col_9 last">
		<div class="switchContainer">
			<div class="stateFeed">FEED</div>
			<div class="switch">|||</div>
			<div class="stateData">DATA</div>
		</div>
	</nav>
</header>

app/views/shared/infinite_scroll.js.erb
$('#events').append('<%= j render(@events) %>');
<% if @events.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@events) %>');
<% else %>
	$('.pagination').remove();
<% end %>
<% sleep 1 %>