config/routes.rb
Babynotes::Application.routes.draw do
  
  devise_for :users

  root to: "pages#index"
  match '/faq', to: "pages#faq"
  match '/team', to: "pages#team"
  match '/privacy_policy', to: "pages#privacy_policy"

  resources :users, only: [:show]

  resources :babies do
    resources :measurements
    resources :events
  end

  resources :timeline, only: [:index]

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  description        :text(255)
#  type               :string(255)
#  happened_at        :datetime
#  baby_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  event_type         :string(255)
#  title              :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Event < ActiveRecord::Base

  # Accessible attributes
  # ========================================================
  attr_accessible :title, :description, :happened_at, :event_type, :image

  # Validations
  # ========================================================
  validates_presence_of :title, :description, :happened_at, :baby_id, :event_type

  # Callbacks
  # ========================================================


  # Relationships
  # ========================================================
  belongs_to :baby
  has_attached_file :image, styles: { large: "1000x1000>", medium: "500x500>", small: "250x250>", thumb: "100x100>" }

  # Scopes
  # ========================================================

  # Static functions
  # ========================================================


  # Instance methods
  # ========================================================


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'will_paginate/array'
	before_filter :authenticate_user!
  before_filter :user_owns_baby
  before_filter :baby_owns_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = @baby.events.order("happened_at DESC").page(params[:page]).per_page(6)
    respond_to do |format|
      format.html
      format.js {render "shared/infinite_scroll"}
    end

  end

  def new
    @event = @baby.events.new
  end

  def create
    @event = @baby.events.new(params[:event])

    if @event.save
      flash[:success] = "Timeline event logged!"
      redirect_to baby_path(@baby)
    else
      render "new"
    end
  end

  def edit
  end

  def update
     if @event.update_attributes(params[:event])
      flash[:success] = "Event updated!"
      redirect_to baby_path(@baby)
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy
    redirect_to baby_path(@baby)
  end
      
end

app/helpers/events_helper.rb
module EventsHelper
	def getEventTypes
		['No type',
			'First Time Sitting',
			'First Time Crawling',
			'First Time Standing',
			'First Time Walking',
			'Starting to Teeth',
			'First Word',
			'First Sentence',
			'Food',
			'Bowel Movement',
			'Spit up',
			'Sick',
			'Crying']
	end
end

app/views/events/_event.html.erb
<div class="event">
	<h4><%= link_to event.title, edit_baby_event_path(@baby, event)  %></h4>
	<span class="content">
		<p><%= event.description %></p>
	</span>

	<span class="timestamp">
		<p>Happened at <%= event.happened_at %>, <%= time_ago_in_words(event.happened_at) %> ago.</p>
	</span>
	This event is of type: <%= event.event_type %>
	<%= link_to "Delete", baby_event_path(@baby, event), :confirm => 'Are you sure?', method: :delete %>
</div>

app/views/events/_forms.html.erb
	<%= render 'shared/error_messages', object: f.object %>
	<div class="control-group">
		<% event_types = getEventTypes() %>
		<%= f.label :title %>
		<%= f.text_field :title, placeholder: "Event's title" %>
	  <%= f.label :description %>
	  <%= f.text_area :description, placeholder: "Event's description" %>
	  <%= f.label :event_type %>
	  <%= f.select(:event_type, options_for_select(event_types))%>
	  <%= f.label :happened_at %>
	  <%= f.datetime_select :happened_at, placeholder: "When it happened" %>
	  <%= f.label :image %>
	  <%= f.file_field :image %>
	</div>

app/views/events/_timeline.html.erb
<% javascript_include_tag :defaults, 'infinite_scroll' %>
<div id="timeline">
  <div class="row">
    <div class="span8">
      <h3><%= link_to "Timeline", baby_events_path(@baby) %></h3>
    </div>
    <div class="span4">
     <%= link_to "New Event", new_baby_event_path(@baby), class: "btn pull-right" %>
    </div>
    <div class="span8">
      <% if @baby.events.any? %>
        <div id="events">
          <%= render @events %>
        </div>
        <%= will_paginate @events %>
        <% else %>
        <div class="span8"><%= @baby.name %> has no timeline events recorded!</div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>
<h2>Edit Event <%= @event.description%> For <%= @baby.name %></h2>

<%= form_for [@baby, @event] do |f| %>
  <%= render "forms", f: f %>
  <div class="form-actions">
    <%= f.submit "Update Event", class: "btn btn-primary" %>
    <%= link_to "Cancel", baby_path(@baby), class: "btn btn-danger" %>
  </div>
<% end %>

app/views/events/index.html.erb
<%= link_to "Back to " + @baby.name, baby_path(@baby) %>
<%= render 'timeline' %>

app/views/events/index.js.erb
$('#events').append('<%= j render(@events) %>');
<% if @events.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@events) %>');
<% else %>
	$('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<h2>New Event For <%= @baby.name %></h2>
<%= form_for [@baby, @event] do |f| %>
	<%= render "forms", f: f %>
	<div class="form-actions">
    <%= f.submit "Create Event", class: "btn btn-primary" %>
    <%= link_to "Cancel", baby_path(@baby), class: "btn btn-danger" %>
  </div>
<% end %>