config/routes.rb
Babynotes::Application.routes.draw do
  
  devise_for :users

  root to: "pages#index"
  match '/faq', to: "pages#faq"
  match '/team', to: "pages#team"
  match '/privacy_policy', to: "pages#privacy_policy"

  resources :users, only: [:show]

  resources :babies do
    resources :measurements
    resources :events
  end

  resources :timeline, only: [:index]

end

app/models/baby.rb
# == Schema Information
#
# Table name: babies
#
#  id         :integer          not null, primary key
#  birth      :datetime
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gender     :string(255)
#

class Baby < ActiveRecord::Base

  # Accessible attributes
  # ========================================================
  attr_accessible :birth, :birth_date, :birth_time, :name, :gender
  attr_accessor :birth_date, :birth_time

  # Validations
  # ========================================================
  validates :birth, presence: true
  validates :name, presence: true
  validates :user_id, presence: true
  validates :gender, presence: true

  # Callbacks
  # ========================================================
  before_validation :concatenate_dates
  before_save :clear_dates

  # Relationships
  # ========================================================
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :measurements, dependent: :destroy

  # Scopes
  # ========================================================


  # Static functions
  # ========================================================


  # Instance methods
  # ========================================================


  # Virtual attributes
  # ========================================================
  def birth_date
    if @birth_date.present?
      @birth_date
    elsif birth.present?
      birth.to_date.to_s
    end
  end

  def birth_time
    if @birth_time.present?
      @birth_time
    elsif birth.present?
      birth.strftime('%I:%M%p')
    end
  end

private
  def concatenate_dates
    self.birth = "#{self.birth_date} #{self.birth_time}"
  end

  def clear_dates
    birth_date = birth_time = nil
  end
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_owns_baby, only: [:show, :edit, :update]

  def index
    @babies = current_user.babies
  end

  def show
    @baby = Baby.find(params[:id])
    @events = @baby.events.order("happened_at DESC").paginate(page: params[:page]).per_page(6)
    respond_to do |format|
      format.html
      format.js { render "shared/infinite_scroll" }
    end

  end

  def new
    @baby = Baby.new
  end

  def create
    @baby = current_user.babies.new(params[:baby])
    if @baby.save
      flash[:success] = "Baby added!"
      redirect_to babies_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @baby.update_attributes(params[:baby])
      flash[:success] = "Baby updated!"
      redirect_to baby_path(@baby)
    else
      render "edit"
    end
  end
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_baby.html.erb
<div class="baby span4">
  <h3><%= link_to baby.name, baby %></h3>
  <p>Born <%=l baby.birth %></p>
  <p>Gender
  <%if baby.gender%>
  	<%= baby.gender%>
  <% else %>
  	<%= "Unknown" %>
  <% end %>
	</p>
</div>

app/views/babies/index.html.erb
<% provide(:title, "Your Babies") %>
<%= link_to "New Baby", new_baby_path(@baby), class: "btn pull-right" %>
<h2>Your Babies</h2>

<div class="row">
  <% if @babies.nil? %>
    <div class="span12">
      <p>You have no babies!</p>
    </div>
  <% else %>
    <%= render @babies %>
  <% end %>
</div>

app/views/babies/new.html.erb
<div class="row">
  <div class="span12">
    <div class="well">
      <h1>Making baby</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <div class="well">
      <%= form_for @baby, html: { class: 'form-horizontal' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="control-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "What is your baby's name?" %>
          <%= f.label :gender %>
          <%= f.select(:gender, ['Male','Female']) %>
          <%= f.label :birth, "Birth Date" %>
          <%= f.datetime_select :birth %>
        </div>
        <div class="form-actions">
          <%= f.submit "Add Baby", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/babies/show.html.erb
<% provide(:title, @baby.name) %>
<h2><%= @baby.name %></h2>

<div class="row">
  <div class="span8">
    <h3>Measurements</h3>
  </div>
  <div class="span4">
    <%= link_to "New Measurement", new_baby_measurement_path(@baby), class: "btn pull-right" %>
  </div>
</div>

<table class="table table-striped table-bordered">
  <% if @baby.measurements.empty? %>
    <tr>
      <td><%= @baby.name %> has no measurements!</td>
    </tr>
  <% else %>
    <tr>
      <th>Measurement Taken</th>
      <th>Height (inches)</th>
      <th>Weight (pounds)</th>
    </tr>
    <%= render @baby.measurements %>
  <% end %>
</table>
<%= render 'events/timeline' %>